#!/usr/bin/env python3
"""Remove hard-coded ambiente pages from index.html that are auto-generated by config.js"""

import re

# Read the file
with open('c:/Eletrize/novo modelo/Dashboard-Template/index.html', 'r', encoding='utf-8') as f:
    content = f.read()

# Pages to remove (these are auto-generated from config.js)
pages_to_remove = [
    # Main environment pages (must be generated from config)
    'ambiente1', 'ambiente2', 'ambiente3', 'ambiente4', 'ambiente5',
    'ambiente6', 'ambiente7', 'ambiente8', 'ambiente9',
    # Sub-pages that were already removed (keeping for reference)
    # 'ambiente1-luzes', 'ambiente1-cortinas',
    # 'ambiente3-luzes', 'ambiente3-cortinas',
    # etc...
]

removed_count = 0

for page_name in pages_to_remove:
    # Pattern to match the entire page definition
    # Format: "page-name": () => `...content...`,
    pattern = r'^\s*"' + re.escape(page_name) + r'":\s*\(\)\s*=>\s*`.*?^\s*`,\s*$'
    
    matches = list(re.finditer(pattern, content, re.MULTILINE | re.DOTALL))
    
    if matches:
        content = re.sub(pattern, '', content, flags=re.MULTILINE | re.DOTALL)
        removed_count += 1
        print(f"✓ Removido: {page_name}")
    else:
        print(f"✗ Não encontrado: {page_name}")

# Write back
with open('c:/Eletrize/novo modelo/Dashboard-Template/index.html', 'w', encoding='utf-8', newline='') as f:
    f.write(content)

print(f"\n✅ Concluído! {removed_count} páginas removidas.")
print("Agora as páginas de luzes e cortinas serão geradas pelo config.js")
