create table if not exists public.user_access_profiles (
  user_id uuid primary key references auth.users (id) on delete cascade,
  role text not null default 'morador',
  display_name text not null default '',
  is_admin boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint user_access_profiles_role_check
    check (role in ('admin', 'morador', 'convidado'))
);

create table if not exists public.user_environment_access (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users (id) on delete cascade,
  environment_key text not null,
  can_view boolean not null default true,
  can_control boolean not null default true,
  can_create_scenes boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint user_environment_access_unique unique (user_id, environment_key)
);

create table if not exists public.environment_device_registry (
  id bigint generated by default as identity primary key,
  environment_key text not null,
  device_id text not null,
  device_type text not null default '',
  device_name text not null default '',
  created_at timestamptz not null default now(),
  constraint environment_device_registry_unique unique (environment_key, device_id)
);

alter table public.user_access_profiles enable row level security;
alter table public.user_environment_access enable row level security;
alter table public.environment_device_registry enable row level security;

drop policy if exists "users can read own access profile" on public.user_access_profiles;
create policy "users can read own access profile"
on public.user_access_profiles
for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists "users can read own environment access" on public.user_environment_access;
create policy "users can read own environment access"
on public.user_environment_access
for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists "authenticated can read environment registry" on public.environment_device_registry;
create policy "authenticated can read environment registry"
on public.environment_device_registry
for select
to authenticated
using (true);

create or replace function public.set_access_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists user_access_profiles_set_updated_at on public.user_access_profiles;
create trigger user_access_profiles_set_updated_at
before update on public.user_access_profiles
for each row
execute function public.set_access_updated_at();

drop trigger if exists user_environment_access_set_updated_at on public.user_environment_access;
create trigger user_environment_access_set_updated_at
before update on public.user_environment_access
for each row
execute function public.set_access_updated_at();

insert into public.environment_device_registry (
  environment_key,
  device_id,
  device_type,
  device_name
)
values
  ('ambiente1','356','appletv','Apple TV'),
  ('ambiente1','357','bluray','Blu-ray'),
  ('ambiente1','355','clarotv','Claro TV'),
  ('ambiente1','347','comfort','home'),
  ('ambiente1','301','lights','Painel'),
  ('ambiente1','340','lights','Spots'),
  ('ambiente1','114','music','Musica'),
  ('ambiente1','354','system','Auxiliar'),
  ('ambiente1','362','tv','Televisao'),
  ('ambiente10','180','comfort','Suite Master'),
  ('ambiente10','52','curtains','Cortina'),
  ('ambiente2','366','comfort','Ar Condicionado'),
  ('ambiente2','374','curtains','Todas'),
  ('ambiente2','375','curtains','Todas'),
  ('ambiente2','302','lights','Canjiquinha'),
  ('ambiente2','303','lights','Hall Entrada'),
  ('ambiente2','304','lights','Spots'),
  ('ambiente2','305','lights','Sanca'),
  ('ambiente2','342','lights','Spots Dimmer'),
  ('ambiente2','344','lights','Lustre'),
  ('ambiente3','349','comfort','Ar Condicionado'),
  ('ambiente3','368','curtains','Todas'),
  ('ambiente3','369','curtains','Todas'),
  ('ambiente3','370','curtains','Todas'),
  ('ambiente3','371','curtains','Todas'),
  ('ambiente3','123','games','Games'),
  ('ambiente3','306','lights','Spots'),
  ('ambiente3','307','lights','Churrasqueira'),
  ('ambiente3','341','lights','Pendente'),
  ('ambiente3','124','music','Musica'),
  ('ambiente3','353','music','Musica'),
  ('ambiente3','365','roku','Roku'),
  ('ambiente3','363','tv','Televisao'),
  ('ambiente4','130','hidromassagem','Hidromassagem'),
  ('ambiente4','308','lights','Corredor Espeto'),
  ('ambiente4','310','lights','Piscina'),
  ('ambiente4','59','lights','LED Piscina'),
  ('ambiente5','350','comfort','Ar Condicionado'),
  ('ambiente5','373','curtains','Cortina'),
  ('ambiente6','316','lights','Trilho'),
  ('ambiente7','379','comfort','Ar Condicionado'),
  ('ambiente7','382','tv','Televisao'),
  ('ambiente8','55','clarotv','Claro TV'),
  ('ambiente8','188','comfort','Suite Milena'),
  ('ambiente8','51','curtains','Cortina'),
  ('ambiente8','54','music','Musica'),
  ('ambiente8','53','tv','Televisao'),
  ('ambiente9','180','comfort','Suite Master'),
  ('ambiente9','52','curtains','Cortina')
on conflict (environment_key, device_id) do update
set
  device_type = excluded.device_type,
  device_name = excluded.device_name;

-- Example admin profile:
-- insert into public.user_access_profiles (user_id, role, display_name, is_admin)
-- values ('USER_UUID_HERE', 'admin', 'Administrador', true)
-- on conflict (user_id) do update
-- set role = excluded.role, display_name = excluded.display_name, is_admin = excluded.is_admin;

-- Example guest profile:
-- insert into public.user_access_profiles (user_id, role, display_name, is_admin)
-- values ('USER_UUID_HERE', 'convidado', 'Convidado Living', false)
-- on conflict (user_id) do update
-- set role = excluded.role, display_name = excluded.display_name, is_admin = excluded.is_admin;

-- Example guest permissions:
-- insert into public.user_environment_access (user_id, environment_key, can_view, can_control, can_create_scenes)
-- values
--   ('USER_UUID_HERE', 'ambiente2', true, true, false),
--   ('USER_UUID_HERE', 'ambiente7', true, true, false)
-- on conflict (user_id, environment_key) do update
-- set
--   can_view = excluded.can_view,
--   can_control = excluded.can_control,
--   can_create_scenes = excluded.can_create_scenes;
